apiVersion: v1
kind: Service
metadata:
  name: my-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: my-exporter
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 31888
  type: NodePort
  