apiVersion: v1
kind: Service
metadata:
  name: my-exporter
spec:
  selector:
    app: my-exporter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31888
  type: NodePort
  